apiVersion: v1
kind: ConfigMap
metadata: {name: prom-config, namespace: default}
data:
  # prometheus.yml: |
  global:
    scrape_interval: 5s
  scrape_configs:
    - job_name: 'flask-app'
      static_configs:
        - targets: ['mlops-app:5000']